# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5Nx8OQsJOlSkxkVVNovuuJ7dAcDGML2
"""

# Install necessary libraries
!pip install transformers matplotlib pandas requests ipywidgets

# Import libraries
import sys
import platform
import os
import io
import re
import json
import textwrap
import requests
from transformers import pipeline
import matplotlib.pyplot as plt
import pandas as pd
import ipywidgets as widgets
from IPython.display import display

# Set up Hugging Face token for AI model (replace with your actual token)
HF_TOKEN = 'YOUR_HF_TOKEN'  # Replace with your actual Hugging Face token
headers = {"Authorization": f"Bearer {HF_TOKEN}"}

# Sample Functions for Finance Features:

# 1. Savings Rate Calculator
def calculate_savings_rate(income, savings):
    savings_rate = (savings / income) * 100
    return round(savings_rate, 2)

# 2. Budget Analyzer (50/30/20 Rule)
def analyze_budget(total_income, needs, wants, savings):
    budget = {
        'needs': (needs / total_income) * 100,
        'wants': (wants / total_income) * 100,
        'savings': (savings / total_income) * 100
    }
    return budget

# 3. Debt Payoff Method (Avalanche vs Snowball)
def calculate_debt_payoff(balance, interest_rate, method='avalanche'):
    # Simple logic for snowball vs avalanche (this is basic and can be extended)
    if method == 'avalanche':
        pay_schedule = "Avalanche method: Focus on highest interest first."
    else:
        pay_schedule = "Snowball method: Focus on smallest balance first."
    return pay_schedule

# 4. Basic Investment Portfolio Analyzer (Placeholder function)
def analyze_investment_portfolio(investments):
    # Placeholder function for portfolio analysis
    risk_level = "Moderate"
    return f"Portfolio Risk Level: {risk_level}"

# UI Elements for User Input and Interaction
income_input = widgets.FloatText(value=5000, description="Income:")
savings_input = widgets.FloatText(value=1000, description="Savings:")
needs_input = widgets.FloatText(value=2000, description="Needs:")
wants_input = widgets.FloatText(value=1500, description="Wants:")
debt_input = widgets.FloatText(value=5000, description="Debt Balance:")
interest_input = widgets.FloatText(value=5, description="Interest Rate (%):")
investment_input = widgets.FloatText(value=10000, description="Investment Total:")

# Buttons for actions
savings_button = widgets.Button(description="Calculate Savings Rate")
budget_button = widgets.Button(description="Analyze Budget")
debt_button = widgets.Button(description="Debt Payoff Method")
investment_button = widgets.Button(description="Analyze Investment Portfolio")

# Define button actions (callbacks)
def on_savings_button_clicked(b):
    savings_rate = calculate_savings_rate(income_input.value, savings_input.value)
    print(f"Savings Rate: {savings_rate}%")

def on_budget_button_clicked(b):
    budget = analyze_budget(income_input.value, needs_input.value, wants_input.value, savings_input.value)
    print(f"Budget Analysis (50/30/20 Rule): {budget}")

def on_debt_button_clicked(b):
    payoff_method = calculate_debt_payoff(debt_input.value, interest_input.value)
    print(f"Debt Payoff Method: {payoff_method}")

def on_investment_button_clicked(b):
    portfolio_analysis = analyze_investment_portfolio(investment_input.value)
    print(portfolio_analysis)

# Link buttons to actions
savings_button.on_click(on_savings_button_clicked)
budget_button.on_click(on_budget_button_clicked)
debt_button.on_click(on_debt_button_clicked)
investment_button.on_click(on_investment_button_clicked)

# Display the UI elements in Colab
display(income_input, savings_input, needs_input, wants_input, debt_input, interest_input, investment_input)
display(savings_button, budget_button, debt_button, investment_button)