# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f5Nx8OQsJOlSkxkVVNovuuJ7dAcDGML2
"""

# Personal Finance Chatbot with IBM Granite 3.1 2B Instruct
# Features: AI Chatbot, Language Translation, Savings Plan Analysis

# Install required packages
!pip install -q transformers accelerate gradio torch sentencepiece

import gradio as gr
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import json
from datetime import datetime

# Initialize model and tokenizer
print("Loading IBM Granite 3.1 2B Instruct model...")
model_name = "ibm-granite/granite-3.1-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)

print("Model loaded successfully!")

# Financial advice system prompts
FINANCE_SYSTEM_PROMPT = """You are an expert personal finance advisor. Provide clear, practical advice on:
- Savings strategies and emergency funds
- Tax optimization (401k, IRA, HSA, tax deductions)
- Investment portfolio allocation
- Retirement planning
- Debt management
- Budgeting techniques

Be concise, actionable, and ask clarifying questions when needed."""

TRANSLATION_SYSTEM_PROMPT = """You are a professional translator specializing in financial terminology.
Translate the following text accurately while preserving financial terms and context."""

# Helper function to generate responses
def generate_response(prompt, system_prompt, max_length=512):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": prompt}
    ]

    input_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(input_text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_length,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Extract only the assistant's response
    if "<|assistant|>" in response:
        response = response.split("<|assistant|>")[-1].strip()

    return response

# Feature 1: Finance Chatbot
def finance_chatbot(message, history):
    try:
        # Build context from history
        context = ""
        if history:
            for user_msg, bot_msg in history[-3:]:  # Last 3 exchanges
                context += f"User: {user_msg}\nAssistant: {bot_msg}\n"

        full_prompt = f"{context}User: {message}\nAssistant:"
        response = generate_response(full_prompt, FINANCE_SYSTEM_PROMPT, max_length=400)

        return response
    except Exception as e:
        return f"Error: {str(e)}"

# Feature 2: Language Translation
def translate_text(text, target_language):
    try:
        if not text.strip():
            return "Please enter text to translate."

        prompt = f"Translate the following financial text to {target_language}:\n\n{text}"
        translation = generate_response(prompt, TRANSLATION_SYSTEM_PROMPT, max_length=300)

        return translation
    except Exception as e:
        return f"Translation error: {str(e)}"

# Feature 3: Savings Plan Analysis
def analyze_savings_plan(monthly_income, monthly_expenses, savings_goal, time_horizon):
    try:
        monthly_income = float(monthly_income)
        monthly_expenses = float(monthly_expenses)
        savings_goal = float(savings_goal)
        time_horizon = int(time_horizon)

        # Calculate metrics
        monthly_surplus = monthly_income - monthly_expenses
        total_months = time_horizon * 12
        required_monthly_savings = savings_goal / total_months if total_months > 0 else 0

        # Generate AI analysis
        analysis_prompt = f"""Analyze this savings plan:
- Monthly Income: ${monthly_income:,.2f}
- Monthly Expenses: ${monthly_expenses:,.2f}
- Monthly Surplus: ${monthly_surplus:,.2f}
- Savings Goal: ${savings_goal:,.2f}
- Time Horizon: {time_horizon} years
- Required Monthly Savings: ${required_monthly_savings:,.2f}

Provide a detailed analysis with actionable recommendations."""

        ai_analysis = generate_response(analysis_prompt, FINANCE_SYSTEM_PROMPT, max_length=500)

        # Build detailed report
        report = f"""
📊 SAVINGS PLAN ANALYSIS REPORT
{'='*50}

💰 FINANCIAL OVERVIEW:
• Monthly Income: ${monthly_income:,.2f}
• Monthly Expenses: ${monthly_expenses:,.2f}
• Monthly Surplus: ${monthly_surplus:,.2f}
• Savings Rate: {(monthly_surplus/monthly_income*100):.1f}%

🎯 SAVINGS GOAL:
• Target Amount: ${savings_goal:,.2f}
• Time Horizon: {time_horizon} years ({total_months} months)
• Required Monthly Savings: ${required_monthly_savings:,.2f}

📈 FEASIBILITY ANALYSIS:
"""

        if monthly_surplus >= required_monthly_savings:
            report += f"✅ ACHIEVABLE: Your monthly surplus (${monthly_surplus:,.2f}) exceeds the required savings (${required_monthly_savings:,.2f}).\n"
            report += f"• Extra cushion: ${monthly_surplus - required_monthly_savings:,.2f}/month\n"
            report += f"• Projected savings at current rate: ${monthly_surplus * total_months:,.2f}\n"
        else:
            shortfall = required_monthly_savings - monthly_surplus
            report += f"⚠️ CHALLENGING: You need ${shortfall:,.2f} more per month to reach your goal.\n"
            report += f"• Current trajectory: ${monthly_surplus * total_months:,.2f} in {time_horizon} years\n"
            report += f"• Shortfall: ${savings_goal - (monthly_surplus * total_months):,.2f}\n"

        report += f"\n💡 AI FINANCIAL ADVISOR RECOMMENDATIONS:\n{'-'*50}\n{ai_analysis}\n"

        return report

    except ValueError:
        return "Error: Please enter valid numbers for all fields."
    except Exception as e:
        return f"Analysis error: {str(e)}"

# Build Gradio Interface
with gr.Blocks(theme=gr.themes.Soft(), title="Personal Finance Chatbot") as demo:
    gr.Markdown("""
    # 💰 Personal Finance Chatbot
    ### Intelligent Guidance for Savings, Taxes, and Investments
    *Powered by IBM Granite 3.1 2B Instruct*
    """)

    with gr.Tabs():
        # Tab 1: Finance Chatbot
        with gr.Tab("💬 Finance Advisor Chatbot"):
            gr.Markdown("""
            Ask me anything about:
            - **Savings strategies** and emergency funds
            - **Tax optimization** (401k, IRA, HSA)
            - **Investment advice** and portfolio allocation
            - **Retirement planning**
            - **Debt management** and budgeting
            """)

            chatbot_interface = gr.ChatInterface(
                fn=finance_chatbot,
                examples=[
                    "How much should I save in an emergency fund?",
                    "What's the difference between a 401k and IRA?",
                    "How should I allocate my investment portfolio at age 30?",
                    "What are the best tax deductions for self-employed individuals?",
                    "Should I pay off debt or invest first?"
                ],
                title="",
                retry_btn=None,
                undo_btn=None,
                clear_btn="Clear Chat"
            )

        # Tab 2: Language Translation
        with gr.Tab("🌐 Financial Text Translation"):
            gr.Markdown("""
            Translate financial documents, advice, or terms into different languages.
            Perfect for understanding international finance or communicating with global clients.
            """)

            with gr.Row():
                with gr.Column():
                    input_text = gr.Textbox(
                        label="Enter Financial Text",
                        placeholder="Enter text to translate...",
                        lines=5
                    )
                    target_lang = gr.Dropdown(
                        choices=["Spanish", "French", "German", "Hindi", "Chinese", "Japanese", "Arabic", "Portuguese", "Italian", "Korean"],
                        label="Target Language",
                        value="Spanish"
                    )
                    translate_btn = gr.Button("Translate", variant="primary")

                with gr.Column():
                    translation_output = gr.Textbox(
                        label="Translation",
                        lines=5
                    )

            translate_btn.click(
                fn=translate_text,
                inputs=[input_text, target_lang],
                outputs=translation_output
            )

            gr.Examples(
                examples=[
                    ["A 401(k) is a retirement savings plan that allows employees to contribute pre-tax dollars.", "Spanish"],
                    ["Diversification is key to reducing investment risk.", "French"],
                    ["You should maintain an emergency fund of 3-6 months of expenses.", "Hindi"]
                ],
                inputs=[input_text, target_lang]
            )

        # Tab 3: Savings Plan Analysis
        with gr.Tab("📊 Savings Plan Analyzer"):
            gr.Markdown("""
            Get a comprehensive analysis of your savings plan with AI-powered recommendations.
            Enter your financial details to see if your goals are achievable!
            """)

            with gr.Row():
                with gr.Column():
                    income_input = gr.Number(label="Monthly Income ($)", value=5000)
                    expenses_input = gr.Number(label="Monthly Expenses ($)", value=3500)
                    goal_input = gr.Number(label="Savings Goal ($)", value=50000)
                    horizon_input = gr.Number(label="Time Horizon (years)", value=5)
                    analyze_btn = gr.Button("Analyze My Savings Plan", variant="primary")

                with gr.Column():
                    analysis_output = gr.Textbox(
                        label="Analysis Report",
                        lines=20
                    )

            analyze_btn.click(
                fn=analyze_savings_plan,
                inputs=[income_input, expenses_input, goal_input, horizon_input],
                outputs=analysis_output
            )

    gr.Markdown("""
    ---
    **Note:** This tool provides general financial guidance. Always consult with a certified financial advisor for personalized advice.
    """)

# Launch the application
print("\n" + "="*60)
print("🚀 Launching Personal Finance Chatbot...")
print("="*60)

demo.launch(debug=True, share=True)

# Personal Finance Chatbot with IBM Granite 3.1 2B Instruct
# Features: AI Chatbot, Language Translation, Savings Plan Analysis

# Install required packages
!pip install -q transformers accelerate gradio torch sentencepiece

import gradio as gr
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import json
from datetime import datetime

# Initialize model and tokenizer
print("Loading IBM Granite 3.1 2B Instruct model...")
model_name = "ibm-granite/granite-3.1-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)

print("Model loaded successfully!")

# Financial advice system prompts
FINANCE_SYSTEM_PROMPT = """You are an expert personal finance advisor. Provide clear, practical advice on:
- Savings strategies and emergency funds
- Tax optimization (401k, IRA, HSA, tax deductions)
- Investment portfolio allocation
- Retirement planning
- Debt management
- Budgeting techniques

Be concise, actionable, and ask clarifying questions when needed."""

TRANSLATION_SYSTEM_PROMPT = """You are a professional translator specializing in financial terminology.
Translate the following text accurately while preserving financial terms and context."""

# Helper function to generate responses
def generate_response(prompt, system_prompt, max_length=512):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": prompt}
    ]

    input_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(input_text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_length,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Extract only the assistant's response
    if "<|assistant|>" in response:
        response = response.split("<|assistant|>")[-1].strip()

    return response

# Feature 1: Finance Chatbot
def finance_chatbot(message, history):
    try:
        # Build context from history
        context = ""
        if history:
            for user_msg, bot_msg in history[-3:]:  # Last 3 exchanges
                context += f"User: {user_msg}\nAssistant: {bot_msg}\n"

        full_prompt = f"{context}User: {message}\nAssistant:"
        response = generate_response(full_prompt, FINANCE_SYSTEM_PROMPT, max_length=400)

        return response
    except Exception as e:
        return f"Error: {str(e)}"

# Feature 2: Language Translation
def translate_text(text, target_language):
    try:
        if not text.strip():
            return "Please enter text to translate."

        prompt = f"Translate the following financial text to {target_language}:\n\n{text}"
        translation = generate_response(prompt, TRANSLATION_SYSTEM_PROMPT, max_length=300)

        return translation
    except Exception as e:
        return f"Translation error: {str(e)}"

# Feature 3: Savings Plan Analysis
def analyze_savings_plan(monthly_income, monthly_expenses, savings_goal, time_horizon):
    try:
        monthly_income = float(monthly_income)
        monthly_expenses = float(monthly_expenses)
        savings_goal = float(savings_goal)
        time_horizon = int(time_horizon)

        # Calculate metrics
        monthly_surplus = monthly_income - monthly_expenses
        total_months = time_horizon * 12
        required_monthly_savings = savings_goal / total_months if total_months > 0 else 0

        # Generate AI analysis
        analysis_prompt = f"""Analyze this savings plan:
- Monthly Income: ${monthly_income:,.2f}
- Monthly Expenses: ${monthly_expenses:,.2f}
- Monthly Surplus: ${monthly_surplus:,.2f}
- Savings Goal: ${savings_goal:,.2f}
- Time Horizon: {time_horizon} years
- Required Monthly Savings: ${required_monthly_savings:,.2f}

Provide a detailed analysis with actionable recommendations."""

        ai_analysis = generate_response(analysis_prompt, FINANCE_SYSTEM_PROMPT, max_length=500)

        # Build detailed report
        report = f"""
📊 SAVINGS PLAN ANALYSIS REPORT
{'='*50}

💰 FINANCIAL OVERVIEW:
• Monthly Income: ${monthly_income:,.2f}
• Monthly Expenses: ${monthly_expenses:,.2f}
• Monthly Surplus: ${monthly_surplus:,.2f}
• Savings Rate: {(monthly_surplus/monthly_income*100):.1f}%

🎯 SAVINGS GOAL:
• Target Amount: ${savings_goal:,.2f}
• Time Horizon: {time_horizon} years ({total_months} months)
• Required Monthly Savings: ${required_monthly_savings:,.2f}

📈 FEASIBILITY ANALYSIS:
"""

        if monthly_surplus >= required_monthly_savings:
            report += f"✅ ACHIEVABLE: Your monthly surplus (${monthly_surplus:,.2f}) exceeds the required savings (${required_monthly_savings:,.2f}).\n"
            report += f"• Extra cushion: ${monthly_surplus - required_monthly_savings:,.2f}/month\n"
            report += f"• Projected savings at current rate: ${monthly_surplus * total_months:,.2f}\n"
        else:
            shortfall = required_monthly_savings - monthly_surplus
            report += f"⚠️ CHALLENGING: You need ${shortfall:,.2f} more per month to reach your goal.\n"
            report += f"• Current trajectory: ${monthly_surplus * total_months:,.2f} in {time_horizon} years\n"
            report += f"• Shortfall: ${savings_goal - (monthly_surplus * total_months):,.2f}\n"

        report += f"\n💡 AI FINANCIAL ADVISOR RECOMMENDATIONS:\n{'-'*50}\n{ai_analysis}\n"

        return report

    except ValueError:
        return "Error: Please enter valid numbers for all fields."
    except Exception as e:
        return f"Analysis error: {str(e)}"

# Build Gradio Interface
with gr.Blocks(theme=gr.themes.Soft(), title="Personal Finance Chatbot") as demo:
    gr.Markdown("""
    # 💰 Personal Finance Chatbot
    ### Intelligent Guidance for Savings, Taxes, and Investments
    *Powered by IBM Granite 3.1 2B Instruct*
    """)

    with gr.Tabs():
        # Tab 1: Finance Chatbot
        with gr.Tab("💬 Finance Advisor Chatbot"):
            gr.Markdown("""
            Ask me anything about:
            - **Savings strategies** and emergency funds
            - **Tax optimization** (401k, IRA, HSA)
            - **Investment advice** and portfolio allocation
            - **Retirement planning**
            - **Debt management** and budgeting
            """)

            chatbot_interface = gr.ChatInterface(
                fn=finance_chatbot,
                examples=[
                    "How much should I save in an emergency fund?",
                    "What's the difference between a 401k and IRA?",
                    "How should I allocate my investment portfolio at age 30?",
                    "What are the best tax deductions for self-employed individuals?",
                    "Should I pay off debt or invest first?"
                ],
                title=""
            )

        # Tab 2: Language Translation
        with gr.Tab("🌐 Financial Text Translation"):
            gr.Markdown("""
            Translate financial documents, advice, or terms into different languages.
            Perfect for understanding international finance or communicating with global clients.
            """)

            with gr.Row():
                with gr.Column():
                    input_text = gr.Textbox(
                        label="Enter Financial Text",
                        placeholder="Enter text to translate...",
                        lines=5
                    )
                    target_lang = gr.Dropdown(
                        choices=["Spanish", "French", "German", "Hindi", "Chinese", "Japanese", "Arabic", "Portuguese", "Italian", "Korean"],
                        label="Target Language",
                        value="Spanish"
                    )
                    translate_btn = gr.Button("Translate", variant="primary")

                with gr.Column():
                    translation_output = gr.Textbox(
                        label="Translation",
                        lines=5
                    )

            translate_btn.click(
                fn=translate_text,
                inputs=[input_text, target_lang],
                outputs=translation_output
            )

            gr.Examples(
                examples=[
                    ["A 401(k) is a retirement savings plan that allows employees to contribute pre-tax dollars.", "Spanish"],
                    ["Diversification is key to reducing investment risk.", "French"],
                    ["You should maintain an emergency fund of 3-6 months of expenses.", "Hindi"]
                ],
                inputs=[input_text, target_lang]
            )

        # Tab 3: Savings Plan Analysis
        with gr.Tab("📊 Savings Plan Analyzer"):
            gr.Markdown("""
            Get a comprehensive analysis of your savings plan with AI-powered recommendations.
            Enter your financial details to see if your goals are achievable!
            """)

            with gr.Row():
                with gr.Column():
                    income_input = gr.Number(label="Monthly Income ($)", value=5000)
                    expenses_input = gr.Number(label="Monthly Expenses ($)", value=3500)
                    goal_input = gr.Number(label="Savings Goal ($)", value=50000)
                    horizon_input = gr.Number(label="Time Horizon (years)", value=5)
                    analyze_btn = gr.Button("Analyze My Savings Plan", variant="primary")

                with gr.Column():
                    analysis_output = gr.Textbox(
                        label="Analysis Report",
                        lines=20
                    )

            analyze_btn.click(
                fn=analyze_savings_plan,
                inputs=[income_input, expenses_input, goal_input, horizon_input],
                outputs=analysis_output
            )

    gr.Markdown("""
    ---
    **Note:** This tool provides general financial guidance. Always consult with a certified financial advisor for personalized advice.
    """)

# Launch the application
print("\n" + "="*60)
print("🚀 Launching Personal Finance Chatbot...")
print("="*60)

demo.launch(debug=True, share=True)

# Personal Finance Chatbot with IBM Granite 3.1 2B Instruct
# Features: AI Chatbot, Language Translation, Savings Plan Analysis

# Install required packages
!pip install -q transformers accelerate gradio torch sentencepiece

import gradio as gr
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import json
from datetime import datetime

# Initialize model and tokenizer
print("Loading IBM Granite 3.1 2B Instruct model...")
model_name = "ibm-granite/granite-3.1-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)

print("Model loaded successfully!")

# Financial advice system prompts
FINANCE_SYSTEM_PROMPT = """You are an expert personal finance advisor. Provide clear, practical advice on:
- Savings strategies and emergency funds
- Tax optimization (401k, IRA, HSA, tax deductions)
- Investment portfolio allocation
- Retirement planning
- Debt management
- Budgeting techniques

Be concise, actionable, and ask clarifying questions when needed."""

TRANSLATION_SYSTEM_PROMPT = """You are a professional translator specializing in financial terminology.
Translate the following text accurately while preserving financial terms and context."""

# Helper function to generate responses
def generate_response(prompt, system_prompt, max_length=512):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": prompt}
    ]

    input_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(input_text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_length,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    # Extract only the assistant's response
    if "<|assistant|>" in response:
        response = response.split("<|assistant|>")[-1].strip()

    return response

# Feature 1: Finance Chatbot
def finance_chatbot(message, history):
    try:
        # Build context from history
        context = ""
        if history:
            for user_msg, bot_msg in history[-3:]:  # Last 3 exchanges
                context += f"User: {user_msg}\nAssistant: {bot_msg}\n"

        full_prompt = f"{context}User: {message}\nAssistant:"
        response = generate_response(full_prompt, FINANCE_SYSTEM_PROMPT, max_length=400)

        return response
    except Exception as e:
        return f"Error: {str(e)}"

# Feature 2: Language Translation
def translate_text(text, target_language):
    try:
        if not text.strip():
            return "Please enter text to translate."

        prompt = f"Translate the following financial text to {target_language}:\n\n{text}"
        translation = generate_response(prompt, TRANSLATION_SYSTEM_PROMPT, max_length=300)

        return translation
    except Exception as e:
        return f"Translation error: {str(e)}"

# Feature 3: Savings Plan Analysis
def analyze_savings_plan(monthly_income, monthly_expenses, savings_goal, time_horizon):
    try:
        monthly_income = float(monthly_income)
        monthly_expenses = float(monthly_expenses)
        savings_goal = float(savings_goal)
        time_horizon = int(time_horizon)

        # Calculate metrics
        monthly_surplus = monthly_income - monthly_expenses
        total_months = time_horizon * 12
        required_monthly_savings = savings_goal / total_months if total_months > 0 else 0

        # Generate AI analysis
        analysis_prompt = f"""Analyze this savings plan:
- Monthly Income: ${monthly_income:,.2f}
- Monthly Expenses: ${monthly_expenses:,.2f}
- Monthly Surplus: ${monthly_surplus:,.2f}
- Savings Goal: ${savings_goal:,.2f}
- Time Horizon: {time_horizon} years
- Required Monthly Savings: ${required_monthly_savings:,.2f}

Provide a detailed analysis with actionable recommendations."""

        ai_analysis = generate_response(analysis_prompt, FINANCE_SYSTEM_PROMPT, max_length=500)

        # Build detailed report
        report = f"""
📊 SAVINGS PLAN ANALYSIS REPORT
{'='*50}

💰 FINANCIAL OVERVIEW:
• Monthly Income: ${monthly_income:,.2f}
• Monthly Expenses: ${monthly_expenses:,.2f}
• Monthly Surplus: ${monthly_surplus:,.2f}
• Savings Rate: {(monthly_surplus/monthly_income*100):.1f}%

🎯 SAVINGS GOAL:
• Target Amount: ${savings_goal:,.2f}
• Time Horizon: {time_horizon} years ({total_months} months)
• Required Monthly Savings: ${required_monthly_savings:,.2f}

📈 FEASIBILITY ANALYSIS:
"""

        if monthly_surplus >= required_monthly_savings:
            report += f"✅ ACHIEVABLE: Your monthly surplus (${monthly_surplus:,.2f}) exceeds the required savings (${required_monthly_savings:,.2f}).\n"
            report += f"• Extra cushion: ${monthly_surplus - required_monthly_savings:,.2f}/month\n"
            report += f"• Projected savings at current rate: ${monthly_surplus * total_months:,.2f}\n"
        else:
            shortfall = required_monthly_savings - monthly_surplus
            report += f"⚠️ CHALLENGING: You need ${shortfall:,.2f} more per month to reach your goal.\n"
            report += f"• Current trajectory: ${monthly_surplus * total_months:,.2f} in {time_horizon} years\n"
            report += f"• Shortfall: ${savings_goal - (monthly_surplus * total_months):,.2f}\n"

        report += f"\n💡 AI FINANCIAL ADVISOR RECOMMENDATIONS:\n{'-'*50}\n{ai_analysis}\n"

        return report

    except ValueError:
        return "Error: Please enter valid numbers for all fields."
    except Exception as e:
        return f"Analysis error: {str(e)}"

# Build Gradio Interface
with gr.Blocks(theme=gr.themes.Soft(), title="Personal Finance Chatbot") as demo:
    gr.Markdown("""
    # 💰 Personal Finance Chatbot
    ### Intelligent Guidance for Savings, Taxes, and Investments
    *Powered by IBM Granite 3.1 2B Instruct*
    """)

    with gr.Tabs():
        # Tab 1: Finance Chatbot
        with gr.Tab("💬 Finance Advisor Chatbot"):
            gr.Markdown("""
            Ask me anything about:
            - **Savings strategies** and emergency funds
            - **Tax optimization** (401k, IRA, HSA)
            - **Investment advice** and portfolio allocation
            - **Retirement planning**
            - **Debt management** and budgeting
            """)

            chatbot_interface = gr.ChatInterface(
                fn=finance_chatbot,
                examples=[
                    "How much should I save in an emergency fund?",
                    "What's the difference between a 401k and IRA?",
                    "How should I allocate my investment portfolio at age 30?",
                    "What are the best tax deductions for self-employed individuals?",
                    "Should I pay off debt or invest first?"
                ],
                title=""
            )

        # Tab 2: Language Translation
        with gr.Tab("🌐 Financial Text Translation"):
            gr.Markdown("""
            Translate financial documents, advice, or terms into different languages.
            Perfect for understanding international finance or communicating with global clients.
            """)

            with gr.Row():
                with gr.Column():
                    input_text = gr.Textbox(
                        label="Enter Financial Text",
                        placeholder="Enter text to translate...",
                        lines=5
                    )
                    target_lang = gr.Dropdown(
                        choices=["Spanish", "French", "German", "Hindi", "Chinese", "Japanese", "Arabic", "Portuguese", "Italian", "Korean"],
                        label="Target Language",
                        value="Spanish"
                    )
                    translate_btn = gr.Button("Translate", variant="primary")

                with gr.Column():
                    translation_output = gr.Textbox(
                        label="Translation",
                        lines=5
                    )

            translate_btn.click(
                fn=translate_text,
                inputs=[input_text, target_lang],
                outputs=translation_output
            )

            gr.Examples(
                examples=[
                    ["A 401(k) is a retirement savings plan that allows employees to contribute pre-tax dollars.", "Spanish"],
                    ["Diversification is key to reducing investment risk.", "French"],
                    ["You should maintain an emergency fund of 3-6 months of expenses.", "Hindi"]
                ],
                inputs=[input_text, target_lang]
            )

        # Tab 3: Savings Plan Analysis
        with gr.Tab("📊 Savings Plan Analyzer"):
            gr.Markdown("""
            Get a comprehensive analysis of your savings plan with AI-powered recommendations.
            Enter your financial details to see if your goals are achievable!
            """)

            with gr.Row():
                with gr.Column():
                    income_input = gr.Number(label="Monthly Income ($)", value=5000)
                    expenses_input = gr.Number(label="Monthly Expenses ($)", value=3500)
                    goal_input = gr.Number(label="Savings Goal ($)", value=50000)
                    horizon_input = gr.Number(label="Time Horizon (years)", value=5)
                    analyze_btn = gr.Button("Analyze My Savings Plan", variant="primary")

                with gr.Column():
                    analysis_output = gr.Textbox(
                        label="Analysis Report",
                        lines=20
                    )

            analyze_btn.click(
                fn=analyze_savings_plan,
                inputs=[income_input, expenses_input, goal_input, horizon_input],
                outputs=analysis_output
            )

    gr.Markdown("""
    ---
    **Note:** This tool provides general financial guidance. Always consult with a certified financial advisor for personalized advice.
    """)

# Launch the application
print("\n" + "="*60)
print("🚀 Launching Personal Finance Chatbot...")
print("="*60)

demo.launch(debug=True, share=True)



# Personal Finance Chatbot with IBM Granite 3.1 2B Instruct
# Features: AI Chatbot, Language Translation, Savings Plan Analysis

# Install required packages
!pip install -q transformers accelerate gradio torch sentencepiece

import gradio as gr
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import json
from datetime import datetime

# Initialize model and tokenizer
print("Loading IBM Granite 3.1 2B Instruct model...")
model_name = "ibm-granite/granite-3.1-2b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16
)

print("Model loaded successfully!")

# Financial advice system prompts
FINANCE_SYSTEM_PROMPT = """You are an expert personal finance advisor. Provide clear, practical advice on:
- Savings strategies and emergency funds
- Tax optimization (401k, IRA, HSA, tax deductions)
- Investment portfolio allocation
- Retirement planning
- Debt management
- Budgeting techniques

Be concise, actionable, and ask clarifying questions when needed."""

TRANSLATION_SYSTEM_PROMPT = """You are a professional translator specializing in financial terminology.
Translate the following text accurately while preserving financial terms and context."""

# Helper function to generate responses
def generate_response(prompt, system_prompt, max_length=512):
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": prompt}
    ]

    input_text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(input_text, return_tensors="pt").to(model.device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_length,
            temperature=0.7,
            top_p=0.9,
            do_sample=True,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id
        )

    # Decode only the generated tokens (not the input)
    generated_tokens = outputs[0][inputs['input_ids'].shape[1]:]
    response = tokenizer.decode(generated_tokens, skip_special_tokens=True)

    # Clean up the response
    response = response.strip()

    # Remove any repeated user prompts or system artifacts
    if "User:" in response:
        response = response.split("User:")[0].strip()
    if "<|assistant|>" in response:
        response = response.split("<|assistant|>")[-1].strip()
    if "<|endoftext|>" in response:
        response = response.split("<|endoftext|>")[0].strip()

    return response

# Feature 1: Finance Chatbot
def finance_chatbot(message, history):
    try:
        # Build context from history
        context = ""
        if history:
            for user_msg, bot_msg in history[-3:]:  # Last 3 exchanges
                context += f"User: {user_msg}\nAssistant: {bot_msg}\n"

        full_prompt = f"{context}User: {message}\nAssistant:"
        response = generate_response(full_prompt, FINANCE_SYSTEM_PROMPT, max_length=400)

        return response
    except Exception as e:
        return f"Error: {str(e)}"

# Feature 2: Language Translation
def translate_text(text, target_language):
    try:
        if not text.strip():
            return "Please enter text to translate."

        prompt = f"Translate the following financial text to {target_language}:\n\n{text}"
        translation = generate_response(prompt, TRANSLATION_SYSTEM_PROMPT, max_length=300)

        return translation
    except Exception as e:
        return f"Translation error: {str(e)}"

# Feature 3: Savings Plan Analysis
def analyze_savings_plan(monthly_income, monthly_expenses, savings_goal, time_horizon):
    try:
        monthly_income = float(monthly_income)
        monthly_expenses = float(monthly_expenses)
        savings_goal = float(savings_goal)
        time_horizon = int(time_horizon)

        # Calculate metrics
        monthly_surplus = monthly_income - monthly_expenses
        total_months = time_horizon * 12
        required_monthly_savings = savings_goal / total_months if total_months > 0 else 0

        # Generate AI analysis
        analysis_prompt = f"""Analyze this savings plan:
- Monthly Income: ${monthly_income:,.2f}
- Monthly Expenses: ${monthly_expenses:,.2f}
- Monthly Surplus: ${monthly_surplus:,.2f}
- Savings Goal: ${savings_goal:,.2f}
- Time Horizon: {time_horizon} years
- Required Monthly Savings: ${required_monthly_savings:,.2f}

Provide a detailed analysis with actionable recommendations."""

        ai_analysis = generate_response(analysis_prompt, FINANCE_SYSTEM_PROMPT, max_length=500)

        # Build detailed report
        report = f"""
📊 SAVINGS PLAN ANALYSIS REPORT
{'='*50}

💰 FINANCIAL OVERVIEW:
• Monthly Income: ${monthly_income:,.2f}
• Monthly Expenses: ${monthly_expenses:,.2f}
• Monthly Surplus: ${monthly_surplus:,.2f}
• Savings Rate: {(monthly_surplus/monthly_income*100):.1f}%

🎯 SAVINGS GOAL:
• Target Amount: ${savings_goal:,.2f}
• Time Horizon: {time_horizon} years ({total_months} months)
• Required Monthly Savings: ${required_monthly_savings:,.2f}

📈 FEASIBILITY ANALYSIS:
"""

        if monthly_surplus >= required_monthly_savings:
            report += f"✅ ACHIEVABLE: Your monthly surplus (${monthly_surplus:,.2f}) exceeds the required savings (${required_monthly_savings:,.2f}).\n"
            report += f"• Extra cushion: ${monthly_surplus - required_monthly_savings:,.2f}/month\n"
            report += f"• Projected savings at current rate: ${monthly_surplus * total_months:,.2f}\n"
        else:
            shortfall = required_monthly_savings - monthly_surplus
            report += f"⚠️ CHALLENGING: You need ${shortfall:,.2f} more per month to reach your goal.\n"
            report += f"• Current trajectory: ${monthly_surplus * total_months:,.2f} in {time_horizon} years\n"
            report += f"• Shortfall: ${savings_goal - (monthly_surplus * total_months):,.2f}\n"

        report += f"\n💡 AI FINANCIAL ADVISOR RECOMMENDATIONS:\n{'-'*50}\n{ai_analysis}\n"

        return report

    except ValueError:
        return "Error: Please enter valid numbers for all fields."
    except Exception as e:
        return f"Analysis error: {str(e)}"

# Build Gradio Interface
with gr.Blocks(theme=gr.themes.Soft(), title="Personal Finance Chatbot") as demo:
    gr.Markdown("""
    # 💰 Personal Finance Chatbot
    ### Intelligent Guidance for Savings, Taxes, and Investments
    *Powered by IBM Granite 3.1 2B Instruct*
    """)

    with gr.Tabs():
        # Tab 1: Finance Chatbot
        with gr.Tab("💬 Finance Advisor Chatbot"):
            gr.Markdown("""
            Ask me anything about:
            - **Savings strategies** and emergency funds
            - **Tax optimization** (401k, IRA, HSA)
            - **Investment advice** and portfolio allocation
            - **Retirement planning**
            - **Debt management** and budgeting
            """)

            chatbot_interface = gr.ChatInterface(
                fn=finance_chatbot,
                examples=[
                    "How much should I save in an emergency fund?",
                    "What's the difference between a 401k and IRA?",
                    "How should I allocate my investment portfolio at age 30?",
                    "What are the best tax deductions for self-employed individuals?",
                    "Should I pay off debt or invest first?"
                ],
                title=""
            )

        # Tab 2: Language Translation
        with gr.Tab("🌐 Financial Text Translation"):
            gr.Markdown("""
            Translate financial documents, advice, or terms into different languages.
            Perfect for understanding international finance or communicating with global clients.
            """)

            with gr.Row():
                with gr.Column():
                    input_text = gr.Textbox(
                        label="Enter Financial Text",
                        placeholder="Enter text to translate...",
                        lines=5
                    )
                    target_lang = gr.Dropdown(
                        choices=["Spanish", "French", "German", "Hindi", "Chinese", "Japanese", "Arabic", "Portuguese", "Italian", "Korean"],
                        label="Target Language",
                        value="Spanish"
                    )
                    translate_btn = gr.Button("Translate", variant="primary")

                with gr.Column():
                    translation_output = gr.Textbox(
                        label="Translation",
                        lines=5
                    )

            translate_btn.click(
                fn=translate_text,
                inputs=[input_text, target_lang],
                outputs=translation_output
            )

            gr.Examples(
                examples=[
                    ["A 401(k) is a retirement savings plan that allows employees to contribute pre-tax dollars.", "Spanish"],
                    ["Diversification is key to reducing investment risk.", "French"],
                    ["You should maintain an emergency fund of 3-6 months of expenses.", "Hindi"]
                ],
                inputs=[input_text, target_lang]
            )

        # Tab 3: Savings Plan Analysis
        with gr.Tab("📊 Savings Plan Analyzer"):
            gr.Markdown("""
            Get a comprehensive analysis of your savings plan with AI-powered recommendations.
            Enter your financial details to see if your goals are achievable!
            """)

            with gr.Row():
                with gr.Column():
                    income_input = gr.Number(label="Monthly Income ($)", value=5000)
                    expenses_input = gr.Number(label="Monthly Expenses ($)", value=3500)
                    goal_input = gr.Number(label="Savings Goal ($)", value=50000)
                    horizon_input = gr.Number(label="Time Horizon (years)", value=5)
                    analyze_btn = gr.Button("Analyze My Savings Plan", variant="primary")

                with gr.Column():
                    analysis_output = gr.Textbox(
                        label="Analysis Report",
                        lines=20
                    )

            analyze_btn.click(
                fn=analyze_savings_plan,
                inputs=[income_input, expenses_input, goal_input, horizon_input],
                outputs=analysis_output
            )

    gr.Markdown("""
    ---
    **Note:** This tool provides general financial guidance. Always consult with a certified financial advisor for personalized advice.
    """)

# Launch the application
print("\n" + "="*60)
print("🚀 Launching Personal Finance Chatbot...")
print("="*60)

demo.launch(debug=True, share=True)